<?php

declare(strict_types=1);

namespace Kami\Cocktail\Search;

use Throwable;
use Laravel\Scout\Engines\MeiliSearchEngine;

class MeilisearchActions implements SearchActionsContract
{
    public function __construct(private readonly MeiliSearchEngine $client)
    {
    }

    public function getBarSearchApiKey(?int $barId): ?string
    {
        $searchApiKey = null;
        $keys = $this->client->getKeys();
        foreach ($keys->getResults() as $key) {
            if ($key->getName() === 'bar-assistant') {
                $searchApiKey = $key;
            }
        }

        if (!$searchApiKey) {
            $searchApiKey = $this->client->createKey([
                'actions' => ['search'],
                'indexes' => ['cocktails', 'ingredients'],
                'expiresAt' => null,
                'name' => 'bar-assistant',
                'description' => 'Client key generated by Bar Assistant Server'
            ]);
        }

        $rules = (object) [
            'cocktails' => (object) [
                'filter' => 'bar_id = ' . $barId,
            ],
            'ingredients' => (object) [
                'filter' => 'bar_id = ' . $barId,
            ]
        ];

        $tenantToken = $this->client->generateTenantToken($searchApiKey->getUid(), $rules, ['apiKey' => $searchApiKey->getKey()]);

        return $tenantToken;
    }

    public function deleteBarSearchApiKey(string $key): void
    {
        $this->client->deleteKey($key);
    }

    public function isAvailable(): bool
    {
        try {
            return $this->client->isHealthy();
        } catch (Throwable) {
            return false;
        }
    }

    public function getVersion(): ?string
    {
        try {
            return $this->client->version()['pkgVersion'];
        } catch (Throwable) {
            return null;
        }
    }

    public function getHost(): ?string
    {
        return config('scout.meilisearch.host');
    }

    public function updateIndexSettings(): void
    {
        $this->client->index('cocktails')->updateSettings([
            'filterableAttributes' => ['tags', 'bar_id'],
            'sortableAttributes' => ['name', 'date'],
            'searchableAttributes' => [
                'name',
                'tags',
                'description',
                'date',
                'short_ingredients',
            ]
        ]);

        $this->client->index('ingredients')->updateSettings([
            'filterableAttributes' => ['category', 'origin', 'bar_id'],
            'sortableAttributes' => ['name', 'category'],
            'searchableAttributes' => [
                'name',
                'description',
                'category',
                'origin',
            ]
        ]);
    }
}
