<?php
declare(strict_types=1);

namespace Kami\Cocktail;

class SearchActions
{
    public static function getPublicApiKey()
    {
        /** @var \Laravel\Scout\Engines\MeiliSearchEngine|\MeiliSearch\Client */
        $engine = app(\Laravel\Scout\EngineManager::class)->engine();

        $key = $engine->createKey([
            'actions' => ['search', 'documents.*', 'indexes.*', 'tasks.*', 'settings.*'],
            'indexes' => ['cocktails', 'ingredients', 'site_search_index'],
            'expiresAt' => null,
            'name' => 'Bar Assistant',
            'description' => 'Client key generated by Bar Assistant Server'
        ]);

        return $key->getKey();
    }

    public static function getPublicDemoApiKey()
    {
        /** @var \Laravel\Scout\Engines\MeiliSearchEngine|\MeiliSearch\Client */
        $engine = app(\Laravel\Scout\EngineManager::class)->engine();

        $key = $engine->createKey([
            'actions' => [
                'search'
            ],
            'indexes' => ['cocktails', 'ingredients', 'site_search_index'],
            'expiresAt' => null,
            'name' => 'Bar Assistant DEMO',
            'description' => 'Client key generated by Bar Assistant Server'
        ]);

        return $key->getKey();
    }

    public static function checkHealth()
    {
        /** @var \Laravel\Scout\Engines\MeiliSearchEngine|\MeiliSearch\Client */
        $engine = app(\Laravel\Scout\EngineManager::class)->engine();

        return $engine->health();
    }

    public static function updateIndexSettings()
    {
        /** @var \Laravel\Scout\Engines\MeiliSearchEngine|\MeiliSearch\Client */
        $engine = app(\Laravel\Scout\EngineManager::class)->engine();

        $engine->index('cocktails')->updateSettings([
            'filterableAttributes' => ['tags', 'user_id'],
            'sortableAttributes' => ['name', 'date'],
            'searchableAttributes' => [
                'name',
                'tags',
                'description',
                'date',
                'source',
            ]
        ]);

        $engine->index('ingredients')->updateSettings([
            'filterableAttributes' => ['category'],
            'sortableAttributes' => ['name']
        ]);
    }

    public static function update($model)
    {
        /** @var \Laravel\Scout\Engines\MeiliSearchEngine|\MeiliSearch\Client */
        $engine = app(\Laravel\Scout\EngineManager::class)->engine();

        $engine->index('site_search_index')->addDocuments([
            $model->toSiteSearchArray()
        ], 'key');
    }

    public static function delete($model)
    {
        /** @var \Laravel\Scout\Engines\MeiliSearchEngine|\MeiliSearch\Client */
        $engine = app(\Laravel\Scout\EngineManager::class)->engine();

        $engine->index('site_search_index')->deleteDocument($model->toSiteSearchArray()['key']);
    }

    public static function flushSearchIndex()
    {
        /** @var \Laravel\Scout\Engines\MeiliSearchEngine|\MeiliSearch\Client */
        $engine = app(\Laravel\Scout\EngineManager::class)->engine();

        $engine->index('site_search_index')->delete();
    }
}
