<?php

declare(strict_types=1);

namespace Kami\Cocktail\Http\Controllers;

use Illuminate\Http\Request;
use Kami\Cocktail\External\Model\Schema;
use Kami\Cocktail\Http\Resources\Generated\GeneratedCocktailFromTextResource;
use Kami\Cocktail\Http\Resources\Generated\GeneratedCocktailTagsResource;
use OpenApi\Attributes as OAT;
use Prism\Prism\Facades\Prism;
use Prism\Prism\Enums\Provider;
use Kami\Cocktail\OpenAPI as BAO;
use Prism\Prism\Schema\ObjectSchema;
use Prism\Prism\Schema\StringSchema;
use Kami\Cocktail\Http\Resources\Generated\GeneratedIngredientResource;
use Kami\Cocktail\Models\Cocktail;
use Kami\Cocktail\Models\Tag;
use Prism\Prism\Schema\ArraySchema;
use Prism\Prism\Schema\NumberSchema;

class GenerateController extends Controller
{
    #[OAT\Post(path: '/generate/ingredient', tags: ['Generation'], operationId: 'completeIngredient', description: 'Suggested ingredient information based on it\'s name, generated by an LLM.', summary: 'Complete ingredient', parameters: [
        new BAO\Parameters\BarIdHeaderParameter(),
    ], requestBody: new OAT\RequestBody(
        required: true,
        content: [
            new OAT\JsonContent(
                type: 'object',
                properties: [
                    new OAT\Property(property: 'name', type: 'string', example: 'Vodka', description: 'Name of the ingredient to complete information for'),
                ],
                required: ['name'],
            ),
        ]
    ))]
    #[BAO\SuccessfulResponse(content: [
        new BAO\WrapObjectWithData(GeneratedIngredientResource::class),
    ])]
    public function completeIngredient(Request $request): GeneratedIngredientResource
    {
        $provider = Provider::tryFrom(config('bar-assistant.ai.provider'));
        $model = config('bar-assistant.ai.model');
        $timeout = config('bar-assistant.ai.timeout');
        $ingredientName = $request->input('name');

        $schema = new ObjectSchema(
            name: 'cocktail_ingredient',
            description: 'Basic information about cocktail ingredient',
            properties: [
                new StringSchema('name', 'The name of the ingredient'),
                new StringSchema('description', 'Helpful description of ingredient (1-2 short paragraphs)'),
                new NumberSchema('strength', 'Alcohol by volume percentage', true),
                new StringSchema('color', 'The predominant color of the ingredient as hex value', true),
                new StringSchema('distilery', 'Name of the distilery producing the ingredient', true),
                new StringSchema('origin', 'The geographical origin of the ingredient', true),
            ],
            requiredFields: ['name', 'description', 'color', 'distilery', 'origin', 'abv']
        );

        $prompt = <<<PROMPT
            Tell me more about {$ingredientName}. Keep description in 1-2 short paragraphs. Color must be represented as a hex value.
        PROMPT;

        $response = Prism::structured()
            ->using($provider, $model)
            ->withSchema($schema)
            ->withPrompt(trim($prompt))
            ->withClientOptions(['timeout' => $timeout])
            ->asStructured();

        return new GeneratedIngredientResource($response->structured);
    }

    #[OAT\Post(path: '/generate/cocktail-tags', tags: ['Generation'], operationId: 'completeCocktailTags', description: 'Suggested cocktail tags, based on existing cocktail information, generated by an LLM.', summary: 'Cocktail tags', parameters: [
        new BAO\Parameters\BarIdHeaderParameter(),
    ], requestBody: new OAT\RequestBody(
        required: true,
        content: [
            new OAT\JsonContent(
                type: 'object',
                properties: [
                    new OAT\Property(property: 'cocktail_id', type: 'string', example: 'Vodka', description: 'Id or slug of the ingredient'),
                ],
                required: ['cocktail_id'],
            ),
        ]
    ))]
    #[BAO\SuccessfulResponse(content: [
        new BAO\WrapObjectWithData(GeneratedCocktailTagsResource::class),
    ])]
    public function completeCocktailTags(Request $request): GeneratedCocktailTagsResource
    {
        $cocktailId = $request->input('cocktail_id');
        $cocktail = Cocktail::where('slug', $cocktailId)
            ->orWhere('id', $cocktailId)
            ->firstOrFail();

        $provider = Provider::tryFrom(config('bar-assistant.ai.provider'));
        $model = config('bar-assistant.ai.model');
        $timeout = config('bar-assistant.ai.timeout');

        $existingTags = Tag::where('bar_id', $cocktail->bar_id)->pluck('name')->implode(', ');

        $schema = new ObjectSchema(
            name: 'cocktail_tags',
            description: 'Cocktail tags',
            properties: [
                new ArraySchema('tags', 'List of recommended cocktail tags', new StringSchema('tag', 'A single cocktail tag')),
            ],
            requiredFields: ['tags']
        );

        $cocktailMarkdown = Schema::fromCocktailModel($cocktail)->toMarkdown();

        $prompt = <<<PROMPT
            Here's a list of existing tags: {$existingTags}. Generate an array of relevant and unique cocktail tags for a cocktail with the following name and instructions. You can generate new tags but try to prefer existing tags. Keep it to 5-6 tags max.
            Cocktail recipe:
            {$cocktailMarkdown}
        PROMPT;

        $response = Prism::structured()
            ->using($provider, $model)
            ->withSchema($schema)
            ->withPrompt(trim($prompt))
            ->withClientOptions(['timeout' => $timeout])
            ->asStructured();

        return new GeneratedCocktailTagsResource($response->structured);
    }

    #[OAT\Post(path: '/generate/cocktail-recipe-from-text', tags: ['Generation'], operationId: 'cocktailRecipeFromText', description: 'Generate a parseable json recipe structure from raw text.', summary: 'Recipe from text', parameters: [
        new BAO\Parameters\BarIdHeaderParameter(),
    ], requestBody: new OAT\RequestBody(
        required: true,
        content: [
            new OAT\JsonContent(
                type: 'object',
                properties: [
                    new OAT\Property(property: 'recipe', type: 'string', example: 'My recipe details are here...', description: 'The raw text of the cocktail recipe to parse')
                ],
                required: ['recipe'],
            ),
        ]
    ))]
    #[BAO\SuccessfulResponse(content: [
        new BAO\WrapObjectWithData(GeneratedCocktailFromTextResource::class),
    ])]
    public function cocktailRecipeFromText(Request $request): GeneratedCocktailFromTextResource
    {
        $provider = Provider::tryFrom(config('bar-assistant.ai.provider'));
        $model = config('bar-assistant.ai.model');
        $timeout = config('bar-assistant.ai.timeout');

        $textRecipe = trim($request->input('recipe'));

        $schema = new ObjectSchema(
            name: 'cocktail_recipe',
            description: 'Cocktail recipe parsed by LLM',
            properties: [
                new StringSchema('name', 'Title of the recipe'),
                new StringSchema('instructions', 'Step by step instructions to prepare the cocktail'),
                new StringSchema('garnish', 'Recommended garnish for the cocktail', true),
                new StringSchema('description', 'Helpful description of the cocktail (1-2 short paragraphs)', true),
                new ArraySchema('ingredients', 'List of ingredients', new ObjectSchema(
                    name: 'cocktail_recipe_ingredient',
                    description: 'Cocktail ingredient',
                    properties: [
                        new StringSchema('name', 'Name of the ingredient'),
                        new NumberSchema('amount', 'The min amount of the ingredient'),
                        new NumberSchema('amount_max', 'The max amount of the ingredient', true),
                        new StringSchema('units', 'Units of the ingredient amount'),
                        new StringSchema('note', 'Additional note about the ingredient', true),
                    ],
                    requiredFields: ['name', 'amount', 'units']
                )),
            ],
            requiredFields: ['name', 'instructions', 'ingredients']
        );

        $prompt = <<<PROMPT
            Here's a text of cocktail recipe. Extract the information in JSON format. Instructions must be a markdown text containg a numbered list of preperation steps.
            Cocktail recipe:
            {$textRecipe}
        PROMPT;

        $response = Prism::structured()
            ->using($provider, $model)
            ->withSchema($schema)
            ->withPrompt(trim($prompt))
            ->withClientOptions(['timeout' => $timeout])
            ->asStructured();

        return new GeneratedCocktailFromTextResource($response->structured);
    }
}
